package listeningrain.cn.blog.dao;

import listeningrain.cn.blog.entity.Contents;
import listeningrain.cn.blog.entity.ContentsExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ContentsMapper {

    int updateCommentNumById(Integer cid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contents
     *
     * @mbg.generated Sat Sep 22 09:55:03 CST 2018
     */
    long countByExample(ContentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contents
     *
     * @mbg.generated Sat Sep 22 09:55:03 CST 2018
     */
    int deleteByExample(ContentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contents
     *
     * @mbg.generated Sat Sep 22 09:55:03 CST 2018
     */
    int deleteByPrimaryKey(Integer cid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contents
     *
     * @mbg.generated Sat Sep 22 09:55:03 CST 2018
     */
    int insert(Contents record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contents
     *
     * @mbg.generated Sat Sep 22 09:55:03 CST 2018
     */
    int insertSelective(Contents record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contents
     *
     * @mbg.generated Sat Sep 22 09:55:03 CST 2018
     */
    List<Contents> selectByExampleWithBLOBs(ContentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contents
     *
     * @mbg.generated Sat Sep 22 09:55:03 CST 2018
     */
    List<Contents> selectByExample(ContentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contents
     *
     * @mbg.generated Sat Sep 22 09:55:03 CST 2018
     */
    Contents selectByPrimaryKey(Integer cid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contents
     *
     * @mbg.generated Sat Sep 22 09:55:03 CST 2018
     */
    int updateByExampleSelective(@Param("record") Contents record, @Param("example") ContentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contents
     *
     * @mbg.generated Sat Sep 22 09:55:03 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") Contents record, @Param("example") ContentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contents
     *
     * @mbg.generated Sat Sep 22 09:55:03 CST 2018
     */
    int updateByExample(@Param("record") Contents record, @Param("example") ContentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contents
     *
     * @mbg.generated Sat Sep 22 09:55:03 CST 2018
     */
    int updateByPrimaryKeySelective(Contents record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contents
     *
     * @mbg.generated Sat Sep 22 09:55:04 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(Contents record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contents
     *
     * @mbg.generated Sat Sep 22 09:55:04 CST 2018
     */
    int updateByPrimaryKey(Contents record);
}