package listeningrain.cn.blog.dao;

import listeningrain.cn.blog.entity.UserShowInformation;
import listeningrain.cn.blog.entity.UserShowInformationExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface UserShowInformationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_show_information
     *
     * @mbg.generated Sat Sep 22 09:55:04 CST 2018
     */
    long countByExample(UserShowInformationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_show_information
     *
     * @mbg.generated Sat Sep 22 09:55:04 CST 2018
     */
    int deleteByExample(UserShowInformationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_show_information
     *
     * @mbg.generated Sat Sep 22 09:55:04 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_show_information
     *
     * @mbg.generated Sat Sep 22 09:55:04 CST 2018
     */
    int insert(UserShowInformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_show_information
     *
     * @mbg.generated Sat Sep 22 09:55:04 CST 2018
     */
    int insertSelective(UserShowInformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_show_information
     *
     * @mbg.generated Sat Sep 22 09:55:04 CST 2018
     */
    List<UserShowInformation> selectByExample(UserShowInformationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_show_information
     *
     * @mbg.generated Sat Sep 22 09:55:04 CST 2018
     */
    UserShowInformation selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_show_information
     *
     * @mbg.generated Sat Sep 22 09:55:04 CST 2018
     */
    int updateByExampleSelective(@Param("record") UserShowInformation record, @Param("example") UserShowInformationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_show_information
     *
     * @mbg.generated Sat Sep 22 09:55:04 CST 2018
     */
    int updateByExample(@Param("record") UserShowInformation record, @Param("example") UserShowInformationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_show_information
     *
     * @mbg.generated Sat Sep 22 09:55:04 CST 2018
     */
    int updateByPrimaryKeySelective(UserShowInformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_show_information
     *
     * @mbg.generated Sat Sep 22 09:55:04 CST 2018
     */
    int updateByPrimaryKey(UserShowInformation record);
}