package listeningrain.cn.blog.entity;

import java.sql.Timestamp;

public class Comments {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.coid
     *
     * @mbg.generated Sat Sep 22 09:55:04 CST 2018
     */
    private Integer coid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.cid
     *
     * @mbg.generated Sat Sep 22 09:55:04 CST 2018
     */
    private Integer cid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.parent
     *
     * @mbg.generated Sat Sep 22 09:55:04 CST 2018
     */
    private Integer parent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.top_level_id
     *
     * @mbg.generated Sat Sep 22 09:55:04 CST 2018
     */
    private Integer topLevelId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.created
     *
     * @mbg.generated Sat Sep 22 09:55:04 CST 2018
     */
    private Timestamp created;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.author
     *
     * @mbg.generated Sat Sep 22 09:55:04 CST 2018
     */
    private String author;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.avator
     *
     * @mbg.generated Sat Sep 22 09:55:04 CST 2018
     */
    private String avator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.author_id
     *
     * @mbg.generated Sat Sep 22 09:55:04 CST 2018
     */
    private Integer authorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.owner_id
     *
     * @mbg.generated Sat Sep 22 09:55:04 CST 2018
     */
    private Integer ownerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.mail
     *
     * @mbg.generated Sat Sep 22 09:55:04 CST 2018
     */
    private String mail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.url
     *
     * @mbg.generated Sat Sep 22 09:55:04 CST 2018
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.ip
     *
     * @mbg.generated Sat Sep 22 09:55:04 CST 2018
     */
    private String ip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.agent
     *
     * @mbg.generated Sat Sep 22 09:55:04 CST 2018
     */
    private String agent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.type
     *
     * @mbg.generated Sat Sep 22 09:55:04 CST 2018
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.status
     *
     * @mbg.generated Sat Sep 22 09:55:04 CST 2018
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.os_name
     *
     * @mbg.generated Sat Sep 22 09:55:04 CST 2018
     */
    private String osName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.address
     *
     * @mbg.generated Sat Sep 22 09:55:04 CST 2018
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.browser
     *
     * @mbg.generated Sat Sep 22 09:55:04 CST 2018
     */
    private String browser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.content
     *
     * @mbg.generated Sat Sep 22 09:55:04 CST 2018
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.coid
     *
     * @return the value of comments.coid
     *
     * @mbg.generated Sat Sep 22 09:55:04 CST 2018
     */
    public Integer getCoid() {
        return coid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.coid
     *
     * @param coid the value for comments.coid
     *
     * @mbg.generated Sat Sep 22 09:55:04 CST 2018
     */
    public void setCoid(Integer coid) {
        this.coid = coid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.cid
     *
     * @return the value of comments.cid
     *
     * @mbg.generated Sat Sep 22 09:55:04 CST 2018
     */
    public Integer getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.cid
     *
     * @param cid the value for comments.cid
     *
     * @mbg.generated Sat Sep 22 09:55:04 CST 2018
     */
    public void setCid(Integer cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.parent
     *
     * @return the value of comments.parent
     *
     * @mbg.generated Sat Sep 22 09:55:04 CST 2018
     */
    public Integer getParent() {
        return parent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.parent
     *
     * @param parent the value for comments.parent
     *
     * @mbg.generated Sat Sep 22 09:55:04 CST 2018
     */
    public void setParent(Integer parent) {
        this.parent = parent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.top_level_id
     *
     * @return the value of comments.top_level_id
     *
     * @mbg.generated Sat Sep 22 09:55:04 CST 2018
     */
    public Integer getTopLevelId() {
        return topLevelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.top_level_id
     *
     * @param topLevelId the value for comments.top_level_id
     *
     * @mbg.generated Sat Sep 22 09:55:04 CST 2018
     */
    public void setTopLevelId(Integer topLevelId) {
        this.topLevelId = topLevelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.created
     *
     * @return the value of comments.created
     *
     * @mbg.generated Sat Sep 22 09:55:04 CST 2018
     */
    public Timestamp getCreated() {
        return created;
    }

    public void setCreated(Timestamp created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.author
     *
     * @return the value of comments.author
     *
     * @mbg.generated Sat Sep 22 09:55:04 CST 2018
     */
    public String getAuthor() {
        return author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.author
     *
     * @param author the value for comments.author
     *
     * @mbg.generated Sat Sep 22 09:55:04 CST 2018
     */
    public void setAuthor(String author) {
        this.author = author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.avator
     *
     * @return the value of comments.avator
     *
     * @mbg.generated Sat Sep 22 09:55:04 CST 2018
     */
    public String getAvator() {
        return avator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.avator
     *
     * @param avator the value for comments.avator
     *
     * @mbg.generated Sat Sep 22 09:55:04 CST 2018
     */
    public void setAvator(String avator) {
        this.avator = avator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.author_id
     *
     * @return the value of comments.author_id
     *
     * @mbg.generated Sat Sep 22 09:55:04 CST 2018
     */
    public Integer getAuthorId() {
        return authorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.author_id
     *
     * @param authorId the value for comments.author_id
     *
     * @mbg.generated Sat Sep 22 09:55:04 CST 2018
     */
    public void setAuthorId(Integer authorId) {
        this.authorId = authorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.owner_id
     *
     * @return the value of comments.owner_id
     *
     * @mbg.generated Sat Sep 22 09:55:04 CST 2018
     */
    public Integer getOwnerId() {
        return ownerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.owner_id
     *
     * @param ownerId the value for comments.owner_id
     *
     * @mbg.generated Sat Sep 22 09:55:04 CST 2018
     */
    public void setOwnerId(Integer ownerId) {
        this.ownerId = ownerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.mail
     *
     * @return the value of comments.mail
     *
     * @mbg.generated Sat Sep 22 09:55:04 CST 2018
     */
    public String getMail() {
        return mail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.mail
     *
     * @param mail the value for comments.mail
     *
     * @mbg.generated Sat Sep 22 09:55:04 CST 2018
     */
    public void setMail(String mail) {
        this.mail = mail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.url
     *
     * @return the value of comments.url
     *
     * @mbg.generated Sat Sep 22 09:55:04 CST 2018
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.url
     *
     * @param url the value for comments.url
     *
     * @mbg.generated Sat Sep 22 09:55:04 CST 2018
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.ip
     *
     * @return the value of comments.ip
     *
     * @mbg.generated Sat Sep 22 09:55:04 CST 2018
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.ip
     *
     * @param ip the value for comments.ip
     *
     * @mbg.generated Sat Sep 22 09:55:04 CST 2018
     */
    public void setIp(String ip) {
        this.ip = ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.agent
     *
     * @return the value of comments.agent
     *
     * @mbg.generated Sat Sep 22 09:55:04 CST 2018
     */
    public String getAgent() {
        return agent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.agent
     *
     * @param agent the value for comments.agent
     *
     * @mbg.generated Sat Sep 22 09:55:04 CST 2018
     */
    public void setAgent(String agent) {
        this.agent = agent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.type
     *
     * @return the value of comments.type
     *
     * @mbg.generated Sat Sep 22 09:55:04 CST 2018
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.type
     *
     * @param type the value for comments.type
     *
     * @mbg.generated Sat Sep 22 09:55:04 CST 2018
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.status
     *
     * @return the value of comments.status
     *
     * @mbg.generated Sat Sep 22 09:55:04 CST 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.status
     *
     * @param status the value for comments.status
     *
     * @mbg.generated Sat Sep 22 09:55:04 CST 2018
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.os_name
     *
     * @return the value of comments.os_name
     *
     * @mbg.generated Sat Sep 22 09:55:04 CST 2018
     */
    public String getOsName() {
        return osName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.os_name
     *
     * @param osName the value for comments.os_name
     *
     * @mbg.generated Sat Sep 22 09:55:04 CST 2018
     */
    public void setOsName(String osName) {
        this.osName = osName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.address
     *
     * @return the value of comments.address
     *
     * @mbg.generated Sat Sep 22 09:55:04 CST 2018
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.address
     *
     * @param address the value for comments.address
     *
     * @mbg.generated Sat Sep 22 09:55:04 CST 2018
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.browser
     *
     * @return the value of comments.browser
     *
     * @mbg.generated Sat Sep 22 09:55:04 CST 2018
     */
    public String getBrowser() {
        return browser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.browser
     *
     * @param browser the value for comments.browser
     *
     * @mbg.generated Sat Sep 22 09:55:04 CST 2018
     */
    public void setBrowser(String browser) {
        this.browser = browser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.content
     *
     * @return the value of comments.content
     *
     * @mbg.generated Sat Sep 22 09:55:04 CST 2018
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.content
     *
     * @param content the value for comments.content
     *
     * @mbg.generated Sat Sep 22 09:55:04 CST 2018
     */
    public void setContent(String content) {
        this.content = content;
    }
}