package listeningrain.cn.blog.entity;

public class Contents {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contents.cid
     *
     * @mbg.generated Sat Sep 22 09:55:03 CST 2018
     */
    private Integer cid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contents.title
     *
     * @mbg.generated Sat Sep 22 09:55:03 CST 2018
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contents.slug
     *
     * @mbg.generated Sat Sep 22 09:55:03 CST 2018
     */
    private String slug;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contents.created
     *
     * @mbg.generated Sat Sep 22 09:55:03 CST 2018
     */
    private Integer created;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contents.modified
     *
     * @mbg.generated Sat Sep 22 09:55:03 CST 2018
     */
    private Integer modified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contents.author_id
     *
     * @mbg.generated Sat Sep 22 09:55:03 CST 2018
     */
    private Integer authorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contents.type
     *
     * @mbg.generated Sat Sep 22 09:55:03 CST 2018
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contents.status
     *
     * @mbg.generated Sat Sep 22 09:55:03 CST 2018
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contents.tags
     *
     * @mbg.generated Sat Sep 22 09:55:03 CST 2018
     */
    private String tags;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contents.categories
     *
     * @mbg.generated Sat Sep 22 09:55:03 CST 2018
     */
    private String categories;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contents.hits
     *
     * @mbg.generated Sat Sep 22 09:55:03 CST 2018
     */
    private Integer hits;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contents.comments_num
     *
     * @mbg.generated Sat Sep 22 09:55:03 CST 2018
     */
    private Integer commentsNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contents.allow_comment
     *
     * @mbg.generated Sat Sep 22 09:55:03 CST 2018
     */
    private Boolean allowComment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contents.allow_ping
     *
     * @mbg.generated Sat Sep 22 09:55:03 CST 2018
     */
    private Boolean allowPing;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contents.allow_feed
     *
     * @mbg.generated Sat Sep 22 09:55:03 CST 2018
     */
    private Boolean allowFeed;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contents.address
     *
     * @mbg.generated Sat Sep 22 09:55:03 CST 2018
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contents.os_name
     *
     * @mbg.generated Sat Sep 22 09:55:03 CST 2018
     */
    private String osName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contents.browser
     *
     * @mbg.generated Sat Sep 22 09:55:03 CST 2018
     */
    private String browser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contents.content
     *
     * @mbg.generated Sat Sep 22 09:55:03 CST 2018
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contents.cid
     *
     * @return the value of contents.cid
     *
     * @mbg.generated Sat Sep 22 09:55:03 CST 2018
     */
    public Integer getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contents.cid
     *
     * @param cid the value for contents.cid
     *
     * @mbg.generated Sat Sep 22 09:55:03 CST 2018
     */
    public void setCid(Integer cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contents.title
     *
     * @return the value of contents.title
     *
     * @mbg.generated Sat Sep 22 09:55:03 CST 2018
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contents.title
     *
     * @param title the value for contents.title
     *
     * @mbg.generated Sat Sep 22 09:55:03 CST 2018
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contents.slug
     *
     * @return the value of contents.slug
     *
     * @mbg.generated Sat Sep 22 09:55:03 CST 2018
     */
    public String getSlug() {
        return slug;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contents.slug
     *
     * @param slug the value for contents.slug
     *
     * @mbg.generated Sat Sep 22 09:55:03 CST 2018
     */
    public void setSlug(String slug) {
        this.slug = slug;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contents.created
     *
     * @return the value of contents.created
     *
     * @mbg.generated Sat Sep 22 09:55:03 CST 2018
     */
    public Integer getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contents.created
     *
     * @param created the value for contents.created
     *
     * @mbg.generated Sat Sep 22 09:55:03 CST 2018
     */
    public void setCreated(Integer created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contents.modified
     *
     * @return the value of contents.modified
     *
     * @mbg.generated Sat Sep 22 09:55:03 CST 2018
     */
    public Integer getModified() {
        return modified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contents.modified
     *
     * @param modified the value for contents.modified
     *
     * @mbg.generated Sat Sep 22 09:55:03 CST 2018
     */
    public void setModified(Integer modified) {
        this.modified = modified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contents.author_id
     *
     * @return the value of contents.author_id
     *
     * @mbg.generated Sat Sep 22 09:55:03 CST 2018
     */
    public Integer getAuthorId() {
        return authorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contents.author_id
     *
     * @param authorId the value for contents.author_id
     *
     * @mbg.generated Sat Sep 22 09:55:03 CST 2018
     */
    public void setAuthorId(Integer authorId) {
        this.authorId = authorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contents.type
     *
     * @return the value of contents.type
     *
     * @mbg.generated Sat Sep 22 09:55:03 CST 2018
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contents.type
     *
     * @param type the value for contents.type
     *
     * @mbg.generated Sat Sep 22 09:55:03 CST 2018
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contents.status
     *
     * @return the value of contents.status
     *
     * @mbg.generated Sat Sep 22 09:55:03 CST 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contents.status
     *
     * @param status the value for contents.status
     *
     * @mbg.generated Sat Sep 22 09:55:03 CST 2018
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contents.tags
     *
     * @return the value of contents.tags
     *
     * @mbg.generated Sat Sep 22 09:55:03 CST 2018
     */
    public String getTags() {
        return tags;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contents.tags
     *
     * @param tags the value for contents.tags
     *
     * @mbg.generated Sat Sep 22 09:55:03 CST 2018
     */
    public void setTags(String tags) {
        this.tags = tags;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contents.categories
     *
     * @return the value of contents.categories
     *
     * @mbg.generated Sat Sep 22 09:55:03 CST 2018
     */
    public String getCategories() {
        return categories;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contents.categories
     *
     * @param categories the value for contents.categories
     *
     * @mbg.generated Sat Sep 22 09:55:03 CST 2018
     */
    public void setCategories(String categories) {
        this.categories = categories;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contents.hits
     *
     * @return the value of contents.hits
     *
     * @mbg.generated Sat Sep 22 09:55:03 CST 2018
     */
    public Integer getHits() {
        return hits;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contents.hits
     *
     * @param hits the value for contents.hits
     *
     * @mbg.generated Sat Sep 22 09:55:03 CST 2018
     */
    public void setHits(Integer hits) {
        this.hits = hits;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contents.comments_num
     *
     * @return the value of contents.comments_num
     *
     * @mbg.generated Sat Sep 22 09:55:03 CST 2018
     */
    public Integer getCommentsNum() {
        return commentsNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contents.comments_num
     *
     * @param commentsNum the value for contents.comments_num
     *
     * @mbg.generated Sat Sep 22 09:55:03 CST 2018
     */
    public void setCommentsNum(Integer commentsNum) {
        this.commentsNum = commentsNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contents.allow_comment
     *
     * @return the value of contents.allow_comment
     *
     * @mbg.generated Sat Sep 22 09:55:03 CST 2018
     */
    public Boolean getAllowComment() {
        return allowComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contents.allow_comment
     *
     * @param allowComment the value for contents.allow_comment
     *
     * @mbg.generated Sat Sep 22 09:55:03 CST 2018
     */
    public void setAllowComment(Boolean allowComment) {
        this.allowComment = allowComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contents.allow_ping
     *
     * @return the value of contents.allow_ping
     *
     * @mbg.generated Sat Sep 22 09:55:03 CST 2018
     */
    public Boolean getAllowPing() {
        return allowPing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contents.allow_ping
     *
     * @param allowPing the value for contents.allow_ping
     *
     * @mbg.generated Sat Sep 22 09:55:03 CST 2018
     */
    public void setAllowPing(Boolean allowPing) {
        this.allowPing = allowPing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contents.allow_feed
     *
     * @return the value of contents.allow_feed
     *
     * @mbg.generated Sat Sep 22 09:55:03 CST 2018
     */
    public Boolean getAllowFeed() {
        return allowFeed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contents.allow_feed
     *
     * @param allowFeed the value for contents.allow_feed
     *
     * @mbg.generated Sat Sep 22 09:55:03 CST 2018
     */
    public void setAllowFeed(Boolean allowFeed) {
        this.allowFeed = allowFeed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contents.address
     *
     * @return the value of contents.address
     *
     * @mbg.generated Sat Sep 22 09:55:03 CST 2018
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contents.address
     *
     * @param address the value for contents.address
     *
     * @mbg.generated Sat Sep 22 09:55:03 CST 2018
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contents.os_name
     *
     * @return the value of contents.os_name
     *
     * @mbg.generated Sat Sep 22 09:55:03 CST 2018
     */
    public String getOsName() {
        return osName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contents.os_name
     *
     * @param osName the value for contents.os_name
     *
     * @mbg.generated Sat Sep 22 09:55:03 CST 2018
     */
    public void setOsName(String osName) {
        this.osName = osName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contents.browser
     *
     * @return the value of contents.browser
     *
     * @mbg.generated Sat Sep 22 09:55:03 CST 2018
     */
    public String getBrowser() {
        return browser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contents.browser
     *
     * @param browser the value for contents.browser
     *
     * @mbg.generated Sat Sep 22 09:55:03 CST 2018
     */
    public void setBrowser(String browser) {
        this.browser = browser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contents.content
     *
     * @return the value of contents.content
     *
     * @mbg.generated Sat Sep 22 09:55:03 CST 2018
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contents.content
     *
     * @param content the value for contents.content
     *
     * @mbg.generated Sat Sep 22 09:55:03 CST 2018
     */
    public void setContent(String content) {
        this.content = content;
    }
}