package listeningrain.cn.blog.entity;

public class Tags {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tags.id
     *
     * @mbg.generated Sat Sep 22 09:55:04 CST 2018
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tags.name
     *
     * @mbg.generated Sat Sep 22 09:55:04 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tags.tid
     *
     * @mbg.generated Sat Sep 22 09:55:04 CST 2018
     */
    private String tid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tags.state
     *
     * @mbg.generated Sat Sep 22 09:55:04 CST 2018
     */
    private Byte state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tags.created
     *
     * @mbg.generated Sat Sep 22 09:55:04 CST 2018
     */
    private Integer created;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tags.updated
     *
     * @mbg.generated Sat Sep 22 09:55:04 CST 2018
     */
    private Integer updated;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tags.id
     *
     * @return the value of tags.id
     *
     * @mbg.generated Sat Sep 22 09:55:04 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tags.id
     *
     * @param id the value for tags.id
     *
     * @mbg.generated Sat Sep 22 09:55:04 CST 2018
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tags.name
     *
     * @return the value of tags.name
     *
     * @mbg.generated Sat Sep 22 09:55:04 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tags.name
     *
     * @param name the value for tags.name
     *
     * @mbg.generated Sat Sep 22 09:55:04 CST 2018
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tags.tid
     *
     * @return the value of tags.tid
     *
     * @mbg.generated Sat Sep 22 09:55:04 CST 2018
     */
    public String getTid() {
        return tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tags.tid
     *
     * @param tid the value for tags.tid
     *
     * @mbg.generated Sat Sep 22 09:55:04 CST 2018
     */
    public void setTid(String tid) {
        this.tid = tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tags.state
     *
     * @return the value of tags.state
     *
     * @mbg.generated Sat Sep 22 09:55:04 CST 2018
     */
    public Byte getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tags.state
     *
     * @param state the value for tags.state
     *
     * @mbg.generated Sat Sep 22 09:55:04 CST 2018
     */
    public void setState(Byte state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tags.created
     *
     * @return the value of tags.created
     *
     * @mbg.generated Sat Sep 22 09:55:04 CST 2018
     */
    public Integer getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tags.created
     *
     * @param created the value for tags.created
     *
     * @mbg.generated Sat Sep 22 09:55:04 CST 2018
     */
    public void setCreated(Integer created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tags.updated
     *
     * @return the value of tags.updated
     *
     * @mbg.generated Sat Sep 22 09:55:04 CST 2018
     */
    public Integer getUpdated() {
        return updated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tags.updated
     *
     * @param updated the value for tags.updated
     *
     * @mbg.generated Sat Sep 22 09:55:04 CST 2018
     */
    public void setUpdated(Integer updated) {
        this.updated = updated;
    }
}