package listeningrain.cn.blog.entity;

public class Users {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.uid
     *
     * @mbg.generated Sat Sep 22 09:55:04 CST 2018
     */
    private Integer uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.username
     *
     * @mbg.generated Sat Sep 22 09:55:04 CST 2018
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.password
     *
     * @mbg.generated Sat Sep 22 09:55:04 CST 2018
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.email
     *
     * @mbg.generated Sat Sep 22 09:55:04 CST 2018
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.home_url
     *
     * @mbg.generated Sat Sep 22 09:55:04 CST 2018
     */
    private String homeUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.screen_name
     *
     * @mbg.generated Sat Sep 22 09:55:04 CST 2018
     */
    private String screenName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.created
     *
     * @mbg.generated Sat Sep 22 09:55:04 CST 2018
     */
    private Integer created;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.activated
     *
     * @mbg.generated Sat Sep 22 09:55:04 CST 2018
     */
    private Integer activated;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.logged
     *
     * @mbg.generated Sat Sep 22 09:55:04 CST 2018
     */
    private Integer logged;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.group_name
     *
     * @mbg.generated Sat Sep 22 09:55:04 CST 2018
     */
    private String groupName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.uid
     *
     * @return the value of users.uid
     *
     * @mbg.generated Sat Sep 22 09:55:04 CST 2018
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.uid
     *
     * @param uid the value for users.uid
     *
     * @mbg.generated Sat Sep 22 09:55:04 CST 2018
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.username
     *
     * @return the value of users.username
     *
     * @mbg.generated Sat Sep 22 09:55:04 CST 2018
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.username
     *
     * @param username the value for users.username
     *
     * @mbg.generated Sat Sep 22 09:55:04 CST 2018
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.password
     *
     * @return the value of users.password
     *
     * @mbg.generated Sat Sep 22 09:55:04 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.password
     *
     * @param password the value for users.password
     *
     * @mbg.generated Sat Sep 22 09:55:04 CST 2018
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.email
     *
     * @return the value of users.email
     *
     * @mbg.generated Sat Sep 22 09:55:04 CST 2018
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.email
     *
     * @param email the value for users.email
     *
     * @mbg.generated Sat Sep 22 09:55:04 CST 2018
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.home_url
     *
     * @return the value of users.home_url
     *
     * @mbg.generated Sat Sep 22 09:55:04 CST 2018
     */
    public String getHomeUrl() {
        return homeUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.home_url
     *
     * @param homeUrl the value for users.home_url
     *
     * @mbg.generated Sat Sep 22 09:55:04 CST 2018
     */
    public void setHomeUrl(String homeUrl) {
        this.homeUrl = homeUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.screen_name
     *
     * @return the value of users.screen_name
     *
     * @mbg.generated Sat Sep 22 09:55:04 CST 2018
     */
    public String getScreenName() {
        return screenName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.screen_name
     *
     * @param screenName the value for users.screen_name
     *
     * @mbg.generated Sat Sep 22 09:55:04 CST 2018
     */
    public void setScreenName(String screenName) {
        this.screenName = screenName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.created
     *
     * @return the value of users.created
     *
     * @mbg.generated Sat Sep 22 09:55:04 CST 2018
     */
    public Integer getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.created
     *
     * @param created the value for users.created
     *
     * @mbg.generated Sat Sep 22 09:55:04 CST 2018
     */
    public void setCreated(Integer created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.activated
     *
     * @return the value of users.activated
     *
     * @mbg.generated Sat Sep 22 09:55:04 CST 2018
     */
    public Integer getActivated() {
        return activated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.activated
     *
     * @param activated the value for users.activated
     *
     * @mbg.generated Sat Sep 22 09:55:04 CST 2018
     */
    public void setActivated(Integer activated) {
        this.activated = activated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.logged
     *
     * @return the value of users.logged
     *
     * @mbg.generated Sat Sep 22 09:55:04 CST 2018
     */
    public Integer getLogged() {
        return logged;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.logged
     *
     * @param logged the value for users.logged
     *
     * @mbg.generated Sat Sep 22 09:55:04 CST 2018
     */
    public void setLogged(Integer logged) {
        this.logged = logged;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.group_name
     *
     * @return the value of users.group_name
     *
     * @mbg.generated Sat Sep 22 09:55:04 CST 2018
     */
    public String getGroupName() {
        return groupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.group_name
     *
     * @param groupName the value for users.group_name
     *
     * @mbg.generated Sat Sep 22 09:55:04 CST 2018
     */
    public void setGroupName(String groupName) {
        this.groupName = groupName;
    }
}