package listeningrain.cn.blog.entity;

public class UserShowInformation {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_show_information.Id
     *
     * @mbg.generated Sat Sep 22 09:55:04 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_show_information.user_id
     *
     * @mbg.generated Sat Sep 22 09:55:04 CST 2018
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_show_information.nickname
     *
     * @mbg.generated Sat Sep 22 09:55:04 CST 2018
     */
    private String nickName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_show_information.age
     *
     * @mbg.generated Sat Sep 22 09:55:04 CST 2018
     */
    private Integer age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_show_information.address
     *
     * @mbg.generated Sat Sep 22 09:55:04 CST 2018
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_show_information.famous_says
     *
     * @mbg.generated Sat Sep 22 09:55:04 CST 2018
     */
    private String famousSays;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_show_information.follower
     *
     * @mbg.generated Sat Sep 22 09:55:04 CST 2018
     */
    private Integer follower;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_show_information.touxiang
     *
     * @mbg.generated Sat Sep 22 09:55:04 CST 2018
     */
    private String touxiang;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_show_information.Id
     *
     * @return the value of user_show_information.Id
     *
     * @mbg.generated Sat Sep 22 09:55:04 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_show_information.Id
     *
     * @param id the value for user_show_information.Id
     *
     * @mbg.generated Sat Sep 22 09:55:04 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_show_information.user_id
     *
     * @return the value of user_show_information.user_id
     *
     * @mbg.generated Sat Sep 22 09:55:04 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_show_information.user_id
     *
     * @param userId the value for user_show_information.user_id
     *
     * @mbg.generated Sat Sep 22 09:55:04 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_show_information.nickname
     *
     * @return the value of user_show_information.nickname
     *
     * @mbg.generated Sat Sep 22 09:55:04 CST 2018
     */
    public String getNickName() {
        return nickName;
    }

    public void setNickName(String nickName) {
        this.nickName = nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_show_information.age
     *
     * @return the value of user_show_information.age
     *
     * @mbg.generated Sat Sep 22 09:55:04 CST 2018
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_show_information.age
     *
     * @param age the value for user_show_information.age
     *
     * @mbg.generated Sat Sep 22 09:55:04 CST 2018
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_show_information.address
     *
     * @return the value of user_show_information.address
     *
     * @mbg.generated Sat Sep 22 09:55:04 CST 2018
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_show_information.address
     *
     * @param address the value for user_show_information.address
     *
     * @mbg.generated Sat Sep 22 09:55:04 CST 2018
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_show_information.famous_says
     *
     * @return the value of user_show_information.famous_says
     *
     * @mbg.generated Sat Sep 22 09:55:04 CST 2018
     */
    public String getFamousSays() {
        return famousSays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_show_information.famous_says
     *
     * @param famousSays the value for user_show_information.famous_says
     *
     * @mbg.generated Sat Sep 22 09:55:04 CST 2018
     */
    public void setFamousSays(String famousSays) {
        this.famousSays = famousSays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_show_information.follower
     *
     * @return the value of user_show_information.follower
     *
     * @mbg.generated Sat Sep 22 09:55:04 CST 2018
     */
    public Integer getFollower() {
        return follower;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_show_information.follower
     *
     * @param follower the value for user_show_information.follower
     *
     * @mbg.generated Sat Sep 22 09:55:04 CST 2018
     */
    public void setFollower(Integer follower) {
        this.follower = follower;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_show_information.touxiang
     *
     * @return the value of user_show_information.touxiang
     *
     * @mbg.generated Sat Sep 22 09:55:04 CST 2018
     */
    public String getTouxiang() {
        return touxiang;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_show_information.touxiang
     *
     * @param touxiang the value for user_show_information.touxiang
     *
     * @mbg.generated Sat Sep 22 09:55:04 CST 2018
     */
    public void setTouxiang(String touxiang) {
        this.touxiang = touxiang;
    }
}